language: python
python:
  - "3.6"
env:
  - FOLDER="docs"
matrix:
  include:

  # Default Python + latest Sphinx + check for broken links
  - env: ADDITIONAL_COMMAND="python -m sphinx docs/ docs/_build/ -b linkcheck -W" FOLDER="docs"

  # A few older Sphinx releases using default Python version and stripped down
  # example from tests/
  - env: SPHINX="==1.6.2" FOLDER="tests"
  - env: SPHINX="==1.6.7" FOLDER="tests"
  - env: SPHINX="==1.7.5" FOLDER="tests"
  - env: SPHINX="==1.8.2" FOLDER="tests"

  # A few Python versions using latest Sphinx release
  - python: "2.7"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "nightly"
  - python: "pypy3"

addons:
  apt:
    packages:
      - pandoc
before_install:
  - npm install katex
  - PATH="${PATH}:$(pwd)/node_modules/.bin"
install:
  - pip install sphinx$SPHINX
  - python setup.py install
script:
  - python -m sphinx $FOLDER $FOLDER/_build/ -c docs/ -b html -W
  - python -m sphinx $FOLDER $FOLDER/_build/ -c docs/ -b latex -W
  # Test server side prerendering
  - katex -V
  - python -m sphinx $FOLDER $FOLDER/_build/ -c docs/ -b html -D katex_prerender=1 -W
  - $ADDITIONAL_COMMAND
