name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      python-version: '3.10'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Sync Python environment
      run: uv sync --group doc

    - name: Tests
      run: |
        uv run python -m sphinx docs docs/_build/ -b html -W
        uv run python -m sphinx docs docs/_build/ -b latex -W
