name: OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      sphinx-version: '5.*'
      python-version: '3.10'
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Sphinx ${{ env.sphinx-version }}
      run: |
        python -V
        python -m pip install --upgrade pip
        pip install "sphinx==${{ env.sphinx-version }}"
        pip install "jinja2<3.1"

    - name: Tests
      run: |
        python -m sphinx docs docs/_build/ -b html -W -C
        python -m sphinx docs docs/_build/ -b latex -W
