name: OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      sphinx-version: '3.*'
      python-version: 3.8
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Sphinx ${{ env.sphinx-version }}
      run: |
        python -V
        python -m pip install --upgrade pip
        pip install "sphinx==${{ env.sphinx-version }}"
        pip install "jinja2<3.1"

    - name: Tests
      run: |
        python -m sphinx docs docs/_build/ -c docs/ -b html -W -D html_theme="alabaster" -D html_theme_options={}
        python -m sphinx docs docs/_build/ -c docs/ -b latex -W
