name: Publish

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build virtualenv

    # PyPI package
    - name: Build Python package
      run: python -m build

    - name: Publish Python package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    # Github release
    - name: Read CHANGELOG
      id: changelog
      run: |
        # Get bullet points from last CHANGELOG entry
        CHANGELOG=$(git diff -U0 HEAD^ HEAD | grep '^[+][\* ]' | sed 's/\+//')
        echo "Got changelog: $CHANGELOG"
        # Support for multiline, see
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        {
          echo 'body<<EOF'
          echo "$CHANGELOG"
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Create release on Github
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.body }}
