name: Sphinx legacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      python-version: '3.9'
    strategy:
      matrix:
        sphinx-version: [ '1.6.7', '1.8.6', '2.4.5', '3.5.4', '4.5.0' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Test HTML builder with sphinx ${{ matrix.sphinx-version }}
      run: |
        uv run --no-project \
          --with "sphinx==${{ matrix.sphinx-version }}" \
          --with "docutils<0.17" \
          --with "jinja2<3.1" \
          --with "sphinxcontrib-applehelp<=1.0.4" \
          --with "sphinxcontrib-devhelp<=1.0.2" \
          --with "sphinxcontrib-htmlhelp<=2.0.1" \
          --with "sphinxcontrib-qthelp<=1.0.3" \
          --with "sphinxcontrib-serializinghtml<=1.1.5" \
          --with "alabaster<=0.7.13" \
          python -m sphinx tests tests/_build/ -b html -W -C -D master_doc=index -D extensions=sphinxcontrib.katex

    - name: Test LaTeX builder with sphinx ${{ matrix.sphinx-version }}
      run: |
        uv run --no-project \
          --with "sphinx==${{ matrix.sphinx-version }}" \
          --with "docutils<0.17" \
          --with "jinja2<3.1" \
          --with "sphinxcontrib-applehelp<=1.0.4" \
          --with "sphinxcontrib-devhelp<=1.0.2" \
          --with "sphinxcontrib-htmlhelp<=2.0.1" \
          --with "sphinxcontrib-qthelp<=1.0.3" \
          --with "sphinxcontrib-serializinghtml<=1.1.5" \
          --with "alabaster<=0.7.13" \
          python -m sphinx tests tests/_build/ -b latex -W -C -D master_doc=index -D extensions=sphinxcontrib.katex
