name: Sphinx legacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      python-version: '3.9'
    strategy:
      matrix:
        sphinx-version: [ '1.6.7', '1.8.6', '2.4.5', '3.5.4', '4.5.0' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Sphinx ${{ matrix.sphinx-version }}
      run: |
        python -V
        uv add "sphinx==${{ matrix.sphinx-version }}"
        uv add "docutils<0.17"
        uv add "jinja2<3.1"
        # Ensure extensions required by sphinx are still compatible
        # (https://github.com/sphinx-doc/sphinx/issues/11890)
        uv add "sphinxcontrib-applehelp<=1.0.4"
        uv add "sphinxcontrib-devhelp<=1.0.2"
        uv add "sphinxcontrib-htmlhelp<=2.0.1"
        uv add "sphinxcontrib-qthelp<=1.0.3"
        uv add "sphinxcontrib-serializinghtml<=1.1.5"
        # Ensure alabaster theme is still compatible
        uv add "alabaster<=0.7.13"
        uv sync --no-dev

    - name: Tests
      run: |
        uv run --no-dev python -m sphinx tests tests/_build/ -b html -W -C -D master_doc=index -D extensions=sphinxcontrib.katex
        uv run --no-dev python -m sphinx tests tests/_build/ -c docs/ -b latex -W
