name: Sphinx legacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      python-version: '3.9'
    strategy:
      matrix:
        sphinx-version: [ '1.6.7', '1.8.6', '2.4.5', '3.5.4', '4.5.0' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Sphinx ${{ matrix.sphinx-version }}
      run: |
        python -V
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pip install "sphinx==${{ matrix.sphinx-version }}"
        pip install "docutils<0.17"
        pip install "jinja2<3.1"
        # Ensure extensions required by sphinx are still compatible
        # (https://github.com/sphinx-doc/sphinx/issues/11890)
        pip install "sphinxcontrib-applehelp<=1.0.4"
        pip install "sphinxcontrib-devhelp<=1.0.2"
        pip install "sphinxcontrib-htmlhelp<=2.0.1"
        pip install "sphinxcontrib-qthelp<=1.0.3"
        pip install "sphinxcontrib-serializinghtml<=1.1.5"

    - name: Tests
      run: |
        python -m sphinx tests tests/_build/ -b html -W -C -D master_doc=index -D extensions=sphinxcontrib.katex
        python -m sphinx tests tests/_build/ -c docs/ -b latex -W
